# Generated by Django 5.2.1 on 2025-08-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takwin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centreformation',
            name='mot_de_passe',
            field=models.CharField(default='', max_length=100),
        ),
    ]
