# Generated by Django 5.2.1 on 2025-08-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takwin', '0002_centreformation_mot_de_passe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centreformation',
            name='mot_de_passe',
            field=models.CharField(default='defaultpassword', max_length=100),
        ),
    ]
