# Generated by Django 5.2.1 on 2025-08-31 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takwin', '0004_alter_centreformation_mot_de_passe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centreformation',
            name='mot_de_passe',
        ),
    ]
