# Generated by Django 5.2.1 on 2025-08-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takwin', '0005_remove_centreformation_mot_de_passe'),
    ]

    operations = [
        migrations.AddField(
            model_name='centreformation',
            name='mot_de_passe',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
